baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Buzz Hugo Theme'

[params]
  description = "An elegant open source and mobile first theme"
  googleAnalytics = "Your tracking code"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]