baseURL: /
languageCode: en-us
title: Buzz Hugo Theme
theme: buzz
googleAnalytics: Your tracking code

params:
  description: An elegant open source and mobile first theme
  socials:
    github: https://github.com/ademilter
    instagram: https://instagram.com/ademilter
    twitter: https://twitter.com/ademilter
