name = "buzz"
license = "MIT"
licenselink = "https://github.com/ademilter/buzz/blob/master/LICENSE.md"
homepage = "https://github.com/ademilter/buzz"
description = "An elegant open source and mobile first theme"
demosite = "https://buzz.vercel.app"
tags = ["minimal", "clean", "responsive", "simple", "portfolio"]
features = ["blog", "themes"]
min_version = 0.0.1

[author]
    name = "Adem ilter"
    homepage = "https://ademilter.com"
